# Generated by Django 5.2.4 on 2025-07-26 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CareerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('current_education_level', models.CharField(choices=[('10_PASS', '10th Pass'), ('11_PUR', 'Pursuing 11th'), ('12_PASS', '12th Pass'), ('12_PUR', 'Pursuing 12th'), ('GRAD_PUR', 'Pursuing Graduation'), ('GRAD', 'Graduated'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer Not to Say')], max_length=1)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('board_of_education', models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('IB', 'International Baccalaureate (IB)'), ('IGCSE', 'IGCSE/Cambridge'), ('OTHER', 'Other')], max_length=15)),
                ('school_name', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('academic_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, default='India', max_length=50)),
                ('preferred_study_location', models.CharField(blank=True, max_length=100)),
                ('language_preferences', models.CharField(blank=True, choices=[('EN', 'English'), ('HI', 'Hindi')], max_length=5)),
                ('dream_career', models.TextField(blank=True)),
                ('preferred_work_environment', models.CharField(blank=True, choices=[('CORPORATE', 'Corporate'), ('STARTUP', 'Startup'), ('GOVT', 'Government'), ('FREELANCE', 'Freelance'), ('NO_PREF', 'No Preference')], max_length=12)),
                ('salary_expectations', models.CharField(blank=True, max_length=25)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('hobbies', models.CharField(blank=True, max_length=200)),
                ('extracurricular_activities', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('preferred_learning_style', models.CharField(blank=True, choices=[('VISUAL', 'Visual (learn by seeing)'), ('AUDITORY', 'Auditory (learn by hearing)'), ('READ_WRITE', 'Reading/Writing (learn by reading/writing)'), ('KINESTHETIC', 'Kinesthetic (learn by doing)'), ('MIXED', 'Mixed/No strong preference')], max_length=15)),
                ('study_time_preference', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10)),
                ('learning_pace', models.CharField(blank=True, choices=[('SLOW', 'Slow'), ('MEDIUM', 'Medium'), ('FAST', 'Fast')], max_length=10)),
                ('group_vs_individual', models.CharField(blank=True, max_length=15)),
                ('device_preference', models.CharField(blank=True, max_length=15)),
                ('personality_type', models.CharField(blank=True, max_length=10)),
                ('learning_aptitude_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_assessment_results', models.JSONField(blank=True, null=True)),
                ('strengths_assessment', models.JSONField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('registration_source', models.CharField(blank=True, max_length=50)),
                ('parent_guardian_contact', models.CharField(blank=True, max_length=15)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('total_courses_enrolled', models.IntegerField(default=0)),
                ('total_courses_completed', models.IntegerField(default=0)),
                ('total_study_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('current_streak', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('family_income_range', models.CharField(blank=True, max_length=30)),
                ('financial_aid_needed', models.BooleanField(default=False)),
                ('support_system', models.CharField(blank=True, max_length=50)),
                ('scholarship_eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges_earned', models.ManyToManyField(blank=True, to='user.badge')),
                ('career_interests', models.ManyToManyField(blank=True, to='user.careerfield')),
                ('soft_skills', models.ManyToManyField(blank=True, related_name='students_soft', to='user.skill')),
                ('technical_skills', models.ManyToManyField(blank=True, related_name='students_technical', to='user.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorite_subjects', models.ManyToManyField(blank=True, related_name='students_favorite', to='user.subject')),
                ('subjects_studied', models.ManyToManyField(blank=True, related_name='students_studied', to='user.subject')),
            ],
        ),
    ]
