# Generated by Django 5.2.4 on 2025-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
